### ISSUE TITLE
backup and restore

### ISSUE THREAD

**Issue by amidia** [Chorss/docker-pgAdmin4#10]
this image is awesome. but i got some difficulties when i want to executes backup and restore process.
fyi. 
i successfully restore data manually in container db-engine
i use this image "centos/postgresql-94-centos7" as database-engine.
any advise how to setup the backup and restore process.
thanks

**Comment by Chorss** [comment]
Hi, I created a simple instruction

1. The container "Pgadmin4" must be connected  with container "centos/postgresql-94-centos7" (docker network). Recommend create docker-compose [Documentaction](https://docs.docker.com/compose/) because you don't have to create a docker network, this is automatically created.
1. run docker-compose
1. Set the paths -> _go to site pgadmin4_ and _File -> Preferences -> Binary the paths set to /usr/bin_
1. Add server and login
1. Well done. You can backup and restore

**EXAMPLE DOCKER-COMPOSE**
This is work my computer(tested)

> version: '3'
services:
  postgres:
    container_name: postgres-centos
    restart: always **#Autostart**
    image: centos/postgresql-94-centos7
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USER=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
  pgadmin4:
    container_name: pgadmin4-centos
    restart: always **#Autostart**
    image: chorss/docker-pgadmin4:latest
    environment:
      - SERVER_MODE=flase
      - SERVER_PORT=5050
    volumes:
      - /home/XXXXX/pgAdmin4:/data # **TODO change PATCH**
    links:
      - postgres
    ports:
      - 5050:5050

PS. Thanks, have a nice day
